apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyclient
  labels:
    app: pyclient
spec:
  selector:
    matchLabels:
      app: pyclient
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pyclient
    spec:
      containers:
      - name: pyclient
        image: pyclient:latest
        imagePullPolicy: Never
