apiVersion: v1
kind: Service
metadata:
  name: pyserver
  labels:
    app: pyserver
    service: pyserver
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: pyserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver-v1
  labels:
    app: pyserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyserver
      version: v1
  template:
    metadata:
      labels:
        app: pyserver
        version: v1
    spec:
      containers:
      - name: pyserver
        image: pyserver:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pyserver
spec:
  hosts:
  - pyserver
  http:
  - route:
    - destination:
        host: pyserver
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pyserver
spec:
  host: pyserver
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2